### ISSUE TITLE
Duplicate Logos

### ISSUE THREAD

**Issue by sorokivski** [TNTU-RS-internship/superset#3]
### for different databases there are same engines:
_**F.E.:**_
spark and hive:
### spark run on top of hive:

![Image](https://github.com/TNTU-RS-internship/superset/assets/65286819/741ae16b-5244-4dce-95e4-94ed4b3b5762)

### so the logos in form look like:

![Image](https://github.com/TNTU-RS-internship/superset/assets/65286819/a299f386-6498-4c69-8542-47ddce9a1e66)

### **but to have different ones for each database connection would be nice**

**Comment by misha1301** [comment]
We can solve it by changing the image seiection logic:

It uses `[database.engine]` key to select image url:
![image](https://github.com/TNTU-RS-internship/superset/assets/61250339/a70d0913-e788-4da9-8cb9-bfb65666182b)
the next function get database image object:
![image](https://github.com/TNTU-RS-internship/superset/assets/61250339/5e5344f1-8b44-4735-8f38-7af8e8440f28)
and that function return image object from superset_text.yml:
![image](https://github.com/TNTU-RS-internship/superset/assets/61250339/9a86fe0d-aa2a-4d4d-b444-f4843fb12c1d)
superset_text.yml:
![image](https://github.com/TNTU-RS-internship/superset/assets/61250339/9864637a-41ac-405f-9f2a-f69871c873b5)

From backend we get a list of available databases with the following keys and we use `engine` key to select images:
![image](https://github.com/TNTU-RS-internship/superset/assets/61250339/71e5977c-2a0b-4b36-ad74-6b95b063f85d)

We can create a new identifier and send it from the backend or use the 'name' key to select images, but this may not be correct because it could lead to naming problems. Because the 'name' keys contain spaces.
